# Generated by Django 3.0 on 2024-03-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20240304_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': 'Lettings'},
        ),
    ]
