# Generated by Django 3.0 on 2024-02-28 12:44

from django.db import migrations


def transfer_data(apps, schema_editor):
    # Gets the 'Address' and 'Letting' models from the original application
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')

    # Gets the 'Address' and 'Letting' models from the new 'lettings' application
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')

    # Transfers data from 'Address'
    for old_address in OldAddress.objects.all():
        new_address = NewAddress(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        new_address.save()

    # Transfers data from 'Letting'
    for old_letting in OldLetting.objects.all():
        new_address = NewAddress.objects.get(
            number=old_letting.address.number,
            street=old_letting.address.street,
            city=old_letting.address.city,
            state=old_letting.address.state,
            zip_code=old_letting.address.zip_code,
            country_iso_code=old_letting.address.country_iso_code
        )
        new_letting = NewLetting(
            title=old_letting.title,
            address=new_address
        )
        new_letting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data)
    ]
