# Generated by Django 3.0 on 2024-02-28 22:15

from django.db import migrations


def transfer_profiles_data(apps, schema_editor):
    # Gets the 'Profile' model from the original application 'oc_lettings_site'
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    # Gets the 'Profile' model from the new application 'profiles'
    NewProfile = apps.get_model('profiles', 'Profile')

    # Transfers data from 'Profile'
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20240228_2153'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_profiles_data),
    ]
