name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run flake8
      run: |
        flake8
    - name: Run Tests and Coverage
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pytest --cov
        coverage report -m --fail-under=80
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker image
      run: |
        docker build -t eraquino/oc-lettings:${{ github.sha }} .
        docker tag eraquino/oc-lettings:${{ github.sha }} eraquino/oc-lettings:latest
        docker push eraquino/oc-lettings:${{ github.sha }}
        docker push eraquino/oc-lettings:latest
    - name: Deploy to Render
      run: |
        curl -X POST -d '' "${{ secrets.RENDER_DEPLOY_HOOK }}"
